<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Easyres') }}</title>
    <!-- Vite CSS -->
    @vite('resources/css/app.css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="bg-zinc-950">
    <section class="min-w-screen min-h-screen flex flex-col justify-start items-center">
        <h1 class="mt-[20vh] text-4xl text-emerald-400 font-[500] tracking-tight">Currículos cadastrados:</h1>
        <div class="rounded-lg overflow-x-scroll overflow-y-hidden border border-zinc-800 mt-4 sm:overflow-x-hidden">
            <table>
                <thead>
                    <tr>
                        <th class="text-zinc-200 bg-zinc-900 border border-zinc-800 border-t-0 px-2 border-l-0">ID</th>
                        <th class="text-zinc-200 bg-zinc-900 border border-zinc-800 border-t-0">Nome</th>
                        <th class="text-zinc-200 bg-zinc-900 border border-zinc-800 border-t-0">Experiências</th>
                        <th class="text-zinc-200 bg-zinc-900 border border-zinc-800 border-t-0"></th>
                        <th class="text-zinc-200 bg-zinc-900 border border-zinc-800 border-t-0 border-r-0"></th>
                    </tr>
                </thead>
                <tbody id="resume-table-body">
                    <!-- generated by <script> -->
                </tbody>
            </table>
        </div>
    </section>

    <script>
        fetch('http://127.0.0.1:8000/api/resume/all')
            .then(response => response.json())
            .then(data => {
                let tabela = document.getElementById('resume-table-body');
                tabela.innerHTML = ""; 
                data.forEach(resume => {
                let workedAt = Array.isArray(resume.worked_at) ? resume.worked_at : JSON.parse(resume.worked_at);
                
                let row = document.createElement('tr');
                row.innerHTML = `
                    <td class="border bg-zinc-900 text-zinc-200 border-zinc-800 border-b-0 border-l-0 py-1 px-2 text-center">${resume.id}</td>
                    <td class="border bg-zinc-900 text-zinc-200 border-zinc-800 border-b-0 py-1 px-2 text-center">${resume.name}</td>
                    <td class="border bg-zinc-900 text-zinc-200 border-zinc-800 border-b-0 border-r-0 py-1 px-2 text-center">${workedAt.length > 1 ? workedAt.join(', ') : workedAt.length == 1 ? workedAt[0] : 'Nenhuma'}</td>
                    <td class="border bg-zinc-900 cursor-pointer text-zinc-200 border-zinc-800 border-b-0 border-r-0 py-2 px-2 text-center" onclick="window.location.href='/resume/${resume.id}/edit'"><i class="bi bi-pencil py-1 px-2 rounded-full bg-zinc-700"></i></td>
                    <td class="border bg-zinc-900 cursor-pointer text-zinc-200 border-zinc-800 border-b-0 border-r-0 py-2 px-2 text-center" onclick="window.location.href='/resume/${resume.id}/delete'"><i class="bi bi-trash py-1 px-2 rounded-full bg-red-800"></i></td>
                `;
                tabela.appendChild(row);
                });
            })
            .catch(error => console.error('Erro ao buscar resumes:', error));
    </script>
</body>
</html>