<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Easyres') }}</title>
    <!-- Vite CSS -->
    @vite('resources/css/app.css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="bg-zinc-950">
    <section class="min-w-screen min-h-screen flex flex-col justify-start items-center">
        <h1 class="text-4xl font-bold text-emerald-500 mt-[20vh]">
            Adicionar currículo:
        </h1>
        
        <form id="add-resume-form" class="flex flex-col rounded border-zinc-900 p-6 mt-4 gap-2 text-zinc-100">
            @csrf
            <div class="flex flex-col max-w-[300px]">
                <label class="ml-1" for="name">Qual o seu nome?</label>
                <input class="rounded-full mt-1 bg-zinc-900 px-3" type="text" id="name" name="name" required>
            </div>
            <div class="flex flex-col max-w-[330px]">
                <label class="ml-1" for="worked_at">Onde você trabalhou ultimamente?</label>
                <div>
                    <input class="rounded-full mt-1 bg-zinc-900 px-3" type="text" id="worked_at" name="worked_at">
                    <button type="button" id="add-xp-btn" class="px-2"><i class="bi bi-plus-circle"></i></button>
                </div>
            </div>
            <div id="xp-added-area" class="mt-2 gap-1 flex flex-wrap max-w-[300px]">
                <!-- Generated by <script> -->
            </div>

            <button type="submit" class="bg-emerald-400 text-zinc-950 font-[600] tracking-tight rounded-full text-xl py-1 px-4">Enviar</button>

            <div id="response-message" class="mt-2"></div>
        </form>
    </section>

    <script>
        const addxpbtn = document.getElementById("add-xp-btn")
        const workedatinput = document.getElementById("worked_at")
        const xpArray = []
        const xpAddedArea =  document.getElementById("xp-added-area") 

        function updateXpAddedArea() {
            xpAddedArea.innerHTML = ""
            xpArray.forEach(xp => {
                const xpDivToAppend = document.createElement("div")
                xpDivToAppend.classList.add('px-6', 'py-1', 'rounded-full', 'border', 'border-emerald-600')
                xpDivToAppend.innerText = xp + " "
                
                const i = document.createElement("i")
                i.classList.add("bi", "bi-x-circle", "text-red-500")
                xpDivToAppend.append(i)
                
                xpDivToAppend.addEventListener('click', () => {
                    xpArray.splice(xpArray.indexOf(xp), 1)
                    updateXpAddedArea()
                })
                
                xpAddedArea.append(xpDivToAppend)
            })
        }

        addxpbtn.addEventListener('click', (e) => {
            e.preventDefault()
            xpArray.push(workedatinput.value)
            updateXpAddedArea()
            workedatinput.value = ""
            workedatinput.focus()
        })

        document.getElementById('add-resume-form').addEventListener('submit', async function(event) {
            event.preventDefault();

            const formData = {
                'name': document.getElementById('name').value,
                'worked_at': xpArray,
            };

            try {
                let response = await fetch("{{ url('/api/resume/create') }}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "Accept": "application/json",
                        "X-CSRF-TOKEN": "{{ csrf_token() }}"
                    },
                    body: JSON.stringify(formData)
                });

                let result = await response.json();

                if (response.ok) {
                    document.getElementById('response-message').innerHTML = `<p style="color:green;">${result.message}</p>`;
                } else {
                    document.getElementById('response-message').innerHTML = `<p style="color:red;">${JSON.stringify(result.errors)}</p>`;
                }
            } catch (error) {
                console.error("Erro:", error);
            }
        });
    </script>
</body>
</html>